[build]
  base = "website/"
  command = "npm run build"
  publish = "dist/"

[dev]
  command = "npm run dev"
  targetPort = 3000
  framework = "#custom"

[[redirects]]
  from = "/graphgen/"
  to = "/graphgen/en/introduction"
  status = 302

[[redirects]]
  from = "/*"
  to = "/graphgen/:splat"
