name: Release

on:
  push:
    branches:
      - 'v[0-9]+'

jobs:
  publish-releases:
    name: Publish Release
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Publish Release
      uses: thefrontside/actions/synchronize-with-npm@v1.9
      env:
        GITHUB_TOKEN: ${{ secrets.FRONTSIDEJACK_GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
